apiVersion: v2
appVersion: nightly-2020-09-10
description: A Helm chart to collect Kubernetes logs with Vector
home: https://vector.dev/
icon: https://vector.dev/press/vector-icon.svg
maintainers:
- email: vector@timber.io
  name: Vector Contributors
name: vector-service
sources:
- https://github.com/timberio/vector/
type: application
version: 0.11.0-nightly-2020-09-10
